/**
 * Chapter 2 — the plant cell, drawn from scratch.
 *
 * ORIGINAL ARTWORK. What is shared with any published cell diagram is the
 * biology (a plant cell has a cellulose wall, one large vacuole, chloroplasts
 * holding stacked grana, a nucleus containing a nucleolus…) and the convention
 * of drawing a cell as a labelled hexagonal cut-away. Those are facts and
 * conventions. Every coordinate here is generated by the code below.
 *
 * WHAT MAKES IT READ AS AN ILLUSTRATION RATHER THAN A DIAGRAM OF BOXES —
 * and it is not perspective, which was the wrong lesson from the first
 * attempt. A modern infographic cell is mostly flat vector; what carries it is
 * DETAIL and PALETTE:
 *
 *   • the wall is three concentric rings, not one outline — outer wall, middle
 *     lamella, plasma membrane — so the boundary has structure to look at;
 *   • every organelle carries its own interior: grana stacks inside each
 *     chloroplast, cristae inside each mitochondrion, ribosome studs along the
 *     rough ER, chromatin threads and pores in the nuclear envelope;
 *   • nothing is a plain ellipse — organelle outlines run through wobbled
 *     control points (`blob`), so no two chloroplasts are the same shape;
 *   • every solid gets a pale `gleam` up and left of centre.
 *
 * COLOUR: the renderer normalises lightness, reading a tint for hue and
 * saturation only. A darker hex does NOT produce a darker shape — use the
 * `shade` layer tone for recession instead.
 *
 * Interaction is `magnify: "part"` — clicking a component lifts THAT component
 * out of the cell, enlarged, leaving the cell in place behind it.
 */

import type { FigureSpec } from "@/lib/sim/types";
import { dots, folds, cisterna, tubule, discStack, stadium, blob, gleam } from "@/lib/sim/draw";

/* ── frame ───────────────────────────────────────────────────────── */

const W = 800;
const H = 545;
const CX = 400;
const CY = 258;
/** Outer radius of the cell. Everything else is derived from it. */
const R = 200;
/** Slight vertical squash — a cell is wider than it is tall on the page, and
 *  a regular hexagon reads as a bolt head. */
const SQUASH = 0.92;

type Pt = [number, number];
const f = (p: Pt) => `${p[0].toFixed(1)},${p[1].toFixed(1)}`;

/**
 * The cell outline at a given radius: a hexagon standing on a flat edge, with
 * its corners rounded. Vertices at 0°, 60°, … put flat edges top and bottom and
 * points left and right, which is the shape a plant cell packs into.
 */
function hexPts(radius: number): Pt[] {
  const pts: Pt[] = [];
  for (let i = 0; i < 6; i++) {
    const a = (Math.PI / 3) * i;
    pts.push([CX + Math.cos(a) * radius, CY + Math.sin(a) * radius * SQUASH]);
  }
  return pts;
}

function toward(from: Pt, to: Pt, d: number): Pt {
  const dx = to[0] - from[0];
  const dy = to[1] - from[1];
  const len = Math.hypot(dx, dy) || 1;
  const t = Math.min(d, len * 0.45) / len;
  return [from[0] + dx * t, from[1] + dy * t];
}

/** Rounded polygon. `reverse` flips the winding, which is how a subpath
 *  becomes a hole rather than a second filled shape. */
function hex(radius: number, round = 22, reverse = false): string {
  const P = reverse ? [...hexPts(radius)].reverse() : hexPts(radius);
  const n = P.length;
  const d: string[] = [];
  const enter = P.map((p, i) => toward(p, P[(i - 1 + n) % n], round));
  const leave = P.map((p, i) => toward(p, P[(i + 1) % n], round));
  d.push(`M${f(enter[0])}`);
  for (let i = 0; i < n; i++) {
    d.push(`Q${f(P[i])} ${f(leave[i])}`);
    d.push(`L${f(enter[(i + 1) % n])}`);
  }
  return d.join(" ") + " Z";
}

/** A ring between two radii — the wall, the lamella, the membrane. */
function ring(outer: number, inner: number, round = 22): string {
  return `${hex(outer, round)} ${hex(inner, round, true)}`;
}

/** A hexagon's inradius shrinks by `t · 2/√3` when you inset its edges by `t`.
 *  Using `radius - t` instead makes every ring visibly thinner than authored. */
const inset = (radius: number, t: number) => radius - t * 1.1547;

const R_LAMELLA = inset(R, 15);
const R_WALL_IN = inset(R, 30);
const R_MEMBRANE = inset(R, 34);
const R_CYTO = inset(R, 37.5);

/* ── where everything sits ───────────────────────────────────────── */

/** Chloroplasts: centre, radii and tilt. Ringed around the vacuole, the way
 *  they actually sit in a mesophyll cell — pressed against the wall by it. */
const CHLORO: [number, number, number, number, number][] = [
  [318, 170, 42, 21, -12],
  [298, 296, 40, 20, 64],
  [392, 352, 42, 21, 6],
  [520, 286, 38, 19, -48],
];

const MITO: [number, number, number, number, number][] = [
  [292, 212, 34, 16, -40],
  [474, 338, 32, 16, 16],
];

const VAC = { cx: 366, cy: 248, rx: 74, ry: 58 };
const NUC = { cx: 492, cy: 212, r: 50 };
const NUCLEOLUS = { cx: 480, cy: 200, r: 17 };

/** Plasmodesmata: channels punched through the wall. Placed ON the boundary,
 *  which is the whole point of them — they are the only structure here that
 *  belongs to two cells at once. */
/** y of the wall band on the flat top and bottom edges. A hexagon standing on
 *  an edge has no vertical sides, so those two edges are the only places a
 *  channel can be drawn straight through the wall without foreshortening. */
const WALL_TOP_OUT = CY - R * 0.866 * SQUASH;
const WALL_TOP_IN = CY - R_WALL_IN * 0.866 * SQUASH;
const WALL_BOT_IN = CY + R_WALL_IN * 0.866 * SQUASH;
const WALL_BOT_OUT = CY + R * 0.866 * SQUASH;

const PLASMO: { x: number; y0: number; y1: number }[] = [
  { x: 352, y0: WALL_TOP_OUT - 3, y1: WALL_TOP_IN + 3 },
  { x: 448, y0: WALL_TOP_OUT - 3, y1: WALL_TOP_IN + 3 },
  { x: 372, y0: WALL_BOT_IN - 3, y1: WALL_BOT_OUT + 3 },
  { x: 456, y0: WALL_BOT_IN - 3, y1: WALL_BOT_OUT + 3 },
];

const chloroPaths = CHLORO.map(([x, y, rx, ry, deg]) =>
  blob(x, y, rx, ry, [1, 0.95, 1.04, 0.96, 1.03, 0.95], deg),
).join(" ");

const granaPaths = CHLORO.map(([x, y, rx, ry, deg]) => {
  const t = (deg * Math.PI) / 180;
  const cos = Math.cos(t);
  const sin = Math.sin(t);
  // Three stacks strung along the organelle's own long axis.
  return [-0.46, 0, 0.46]
    .map((u) => {
      const ox = u * rx * 0.82;
      return discStack(x + ox * cos, y + ox * sin, 3, ry * 0.42, ry * 0.16, ry * 0.36);
    })
    .join(" ");
}).join(" ");

const mitoPaths = MITO.map(([x, y, rx, ry, deg]) =>
  blob(x, y, rx, ry, [1, 0.94, 1.05, 0.95, 1.04, 0.94], deg),
).join(" ");

const cristaePaths = MITO.map(([x, y, rx, ry, deg]) =>
  folds(x, y, rx, ry, 6, deg, 1.55),
).join(" ");

/* ── palette ─────────────────────────────────────────────────────── */

const T = {
  wall: "#5f9c3a",
  lamella: "#8fbf4e",
  membrane: "#f28c28",
  cytoplasm: "#eaf0c2",
  vacuole: "#79c8e0",
  nucleus: "#a768cf",
  nucleolus: "#6f35a0",
  chloroplast: "#43a94c",
  mitochondrion: "#dd6a38",
  golgi: "#d9558e",
  er: "#4f96d6",
  ribosome: "#3862ab",
  peroxisome: "#e8a33c",
  plasmodesma: "#7fae3f",
};

/* ── the plate ───────────────────────────────────────────────────── */

export const plantCellPlate: FigureSpec = {
  kind: "figure",
  figNumber: "Fig. 2.10 (b)",
  title: "A typical plant cell",
  caption:
    "A eukaryotic cell with three things an animal cell never has: a rigid cellulose wall, chloroplasts, and one large central vacuole.",
  altText:
    "A labelled cut-away of a hexagonal plant cell. A layered cellulose wall pierced by plasmodesmata encloses the cytoplasm, which holds a large central vacuole, the nucleus with its nucleolus and chromatin, five chloroplasts with stacked grana, two mitochondria with cristae, the Golgi apparatus, rough endoplasmic reticulum, peroxisomes and free ribosomes. Selecting any component lifts it out of the cell, enlarged, and explains it.",
  viewBox: [W, H],
  magnify: "part",
  parts: [
    {
      id: "cell-wall",
      label: "Cell wall",
      tint: T.wall,
      depth: 0,
      backdrop: true,
      d: ring(R, R_WALL_IN, 24),
      layers: [
        // The middle lamella — the pectin layer that cements neighbouring
        // cells together. Drawn as a paler band inside the wall's thickness.
        { d: ring(R_LAMELLA, R_WALL_IN, 22), as: "light", tint: T.lamella, opacity: 0.85 },
        { d: hex(R_LAMELLA, 22), as: "stroke", width: 1.1, opacity: 0.55 },
      ],
      focus: [200, 128, 96, 88],
      labelAt: [178, 158],
      leaderAt: [236, 176],
      blurb:
        "A rigid jacket of cellulose outside the membrane. It gives the cell its boxy shape, resists the outward push of a full vacuole, and lets water and dissolved minerals pass straight through.",
    },
    {
      id: "plasma-membrane",
      label: "Plasma membrane",
      tint: T.membrane,
      depth: 1,
      backdrop: true,
      d: ring(R_MEMBRANE, R_CYTO, 20),
      focus: [560, 306, 60, 62],
      labelAt: [622, 132],
      leaderAt: [578, 322],
      blurb:
        "A thin, selectively permeable layer pressed against the inside of the wall. The wall decides nothing — this membrane is what actually controls which substances enter and leave the cell.",
    },
    {
      id: "cytoplasm",
      label: "Cytoplasm",
      tint: T.cytoplasm,
      depth: 2,
      backdrop: true,
      d: hex(R_CYTO, 20),
      layers: [
        { d: hex(R_CYTO, 20), as: "light" },
        // Cytoskeleton — the fibre network that holds organelle positions.
        {
          d:
            "M262,196 C320,232 352,338 300,392 M470,140 C512,214 556,268 542,352 " +
            "M240,268 C316,296 400,300 476,330",
          as: "stroke",
          width: 1.1,
          opacity: 0.34,
          dash: "6 7",
        },
      ],
      focus: [316, 400, 68, 52],
      labelAt: [178, 456],
      leaderAt: [340, 420],
      blurb:
        "The jelly-like fluid every organelle sits in, criss-crossed by a scaffold of fine fibres. In a living cell it streams slowly around the vacuole, carrying materials from one part to another.",
    },
    {
      id: "plasmodesmata",
      label: "Plasmodesmata",
      tint: T.plasmodesma,
      depth: 3,
      d: PLASMO.map(({ x, y0, y1 }) => stadium(x - 11, y0, 22, y1 - y0)).join(" "),
      layers: [
        // The channel itself: cytoplasm running through, so it is drawn in the
        // panel colour — a hole, not a stripe.
        {
          d: PLASMO.map(({ x, y0, y1 }) =>
            stadium(x - 4.5, y0 + 4, 9, y1 - y0 - 8),
          ).join(" "),
          as: "panel",
          opacity: 0.85,
        },
      ],
      focus: [PLASMO[0].x - 22, PLASMO[0].y0 - 6, 44, PLASMO[0].y1 - PLASMO[0].y0 + 12],
      labelAt: [622, 92],
      leaderAt: [PLASMO[1].x + 10, PLASMO[1].y0 + 8],
      blurb:
        "Narrow channels tunnelling through the wall to join one cell's cytoplasm to the next. They let neighbouring cells swap water, food and signals without anything crossing a membrane.",
    },
    {
      id: "vacuole",
      label: "Central vacuole",
      tint: T.vacuole,
      depth: 4,
      d: blob(VAC.cx, VAC.cy, VAC.rx, VAC.ry, [1, 0.95, 1.05, 0.96, 1.03, 0.94, 1.04, 0.97]),
      layers: [
        // The tonoplast: the vacuole has a membrane of its own.
        {
          d: blob(VAC.cx, VAC.cy, VAC.rx - 8, VAC.ry - 7, [1, 0.95, 1.05, 0.96, 1.03, 0.94, 1.04, 0.97]),
          as: "stroke",
          width: 1.4,
          opacity: 0.65,
        },
        { d: gleam(VAC.cx, VAC.cy, VAC.rx, VAC.ry), as: "light", opacity: 0.55 },
      ],
      focus: [VAC.cx - VAC.rx, VAC.cy - VAC.ry, VAC.rx * 2, VAC.ry * 2],
      labelAt: [178, 258],
      leaderAt: [280, 250],
      blurb:
        "One huge sac of cell sap filling most of a mature plant cell. Its water pressure pushes outward against the wall and keeps stems and leaves firm — which is why a plant wilts as it dries out.",
    },
    {
      id: "nucleus",
      label: "Nucleus",
      tint: T.nucleus,
      depth: 5,
      d: blob(NUC.cx, NUC.cy, NUC.r, NUC.r * 0.96, [1, 0.98, 1.02, 0.98, 1.01, 0.98, 1.02, 0.99]),
      layers: [
        // Chromatin — the DNA, uncondensed because this cell is not dividing.
        {
          d:
            `M${NUC.cx - 30},${NUC.cy - 6} C${NUC.cx - 14},${NUC.cy - 26} ${NUC.cx + 8},${NUC.cy + 14} ${NUC.cx + 30},${NUC.cy - 8} ` +
            `M${NUC.cx - 26},${NUC.cy + 20} C${NUC.cx - 8},${NUC.cy + 2} ${NUC.cx + 12},${NUC.cy + 34} ${NUC.cx + 30},${NUC.cy + 14} ` +
            `M${NUC.cx - 12},${NUC.cy + 36} C${NUC.cx + 2},${NUC.cy + 22} ${NUC.cx + 16},${NUC.cy + 40} ${NUC.cx + 26},${NUC.cy + 32}`,
          as: "stroke",
          width: 1.5,
          opacity: 0.5,
        },
        // The nuclear envelope, drawn as the double membrane it is.
        {
          d: blob(NUC.cx, NUC.cy, NUC.r - 6, NUC.r * 0.96 - 6, [1, 0.98, 1.02, 0.98, 1.01, 0.98, 1.02, 0.99]),
          as: "stroke",
          width: 1.4,
          opacity: 0.75,
        },
        // Pores through it.
        {
          d: dots(
            [0, 52, 118, 168, 214, 292].map((deg) => {
              const a = (deg * Math.PI) / 180;
              return [
                NUC.cx + Math.cos(a) * (NUC.r - 3),
                NUC.cy + Math.sin(a) * (NUC.r * 0.96 - 3),
              ] as Pt;
            }),
            4.2,
          ),
          as: "shade",
        },
        { d: gleam(NUC.cx, NUC.cy, NUC.r, NUC.r), as: "light", opacity: 0.4 },
      ],
      focus: [NUC.cx - NUC.r, NUC.cy - NUC.r, NUC.r * 2, NUC.r * 2],
      labelAt: [622, 196],
      leaderAt: [530, 212],
      blurb:
        "The control centre, wrapped in a double envelope pierced by pores. It holds the chromatin — the tangled DNA carrying the instructions for everything the cell builds.",
    },
    {
      id: "nucleolus",
      label: "Nucleolus",
      tint: T.nucleolus,
      depth: 6,
      d: blob(NUCLEOLUS.cx, NUCLEOLUS.cy, NUCLEOLUS.r, NUCLEOLUS.r * 0.94, [1, 0.94, 1.06, 0.95, 1.04, 0.96]),
      layers: [
        {
          d: blob(NUCLEOLUS.cx, NUCLEOLUS.cy, NUCLEOLUS.r, NUCLEOLUS.r * 0.94, [1, 0.94, 1.06, 0.95, 1.04, 0.96]),
          as: "shade",
        },
      ],
      focus: [NUCLEOLUS.cx - NUCLEOLUS.r, NUCLEOLUS.cy - NUCLEOLUS.r, NUCLEOLUS.r * 2, NUCLEOLUS.r * 2],
      labelAt: [622, 236],
      leaderAt: [NUCLEOLUS.cx + 14, NUCLEOLUS.cy - 8],
      blurb:
        "The dense round body inside the nucleus. Ribosomal subunits are assembled here, then leave through the nuclear pores to do their work out in the cytoplasm.",
    },
    {
      id: "chloroplast",
      label: "Chloroplasts",
      tint: T.chloroplast,
      depth: 7,
      d: chloroPaths,
      layers: [
        // Grana: the stacks of chlorophyll-bearing discs, in the darker tone.
        { d: granaPaths, as: "shade", opacity: 0.9 },
        ...CHLORO.slice(0, 3).map(([x, y, rx, ry, deg]) => ({
          d: gleam(x, y, rx, ry, deg - 20),
          as: "light" as const,
          opacity: 0.45,
        })),
      ],
      focus: [CHLORO[0][0] - 48, CHLORO[0][1] - 30, 96, 60],
      labelAt: [178, 116],
      leaderAt: [280, 144],
      blurb:
        "Green organelles that trap sunlight and build food from it. The stacks inside hold chlorophyll, the pigment that gives them — and the whole plant — its colour. Animal cells have none.",
    },
    {
      id: "mitochondria",
      label: "Mitochondria",
      tint: T.mitochondrion,
      depth: 8,
      d: mitoPaths,
      layers: [
        { d: cristaePaths, as: "stroke", width: 1.5, opacity: 0.85 },
        { d: gleam(MITO[0][0], MITO[0][1], MITO[0][2], MITO[0][3], -50), as: "light", opacity: 0.45 },
      ],
      focus: [MITO[0][0] - 42, MITO[0][1] - 28, 84, 56],
      labelAt: [178, 208],
      leaderAt: [MITO[0][0] + 24, MITO[0][1] + 6],
      blurb:
        "Where sugar is broken down to release energy, which is why they are called the powerhouses of the cell. The folds inside pack in more membrane for those reactions to run on.",
    },
    {
      id: "er",
      label: "Endoplasmic reticulum",
      tint: T.er,
      depth: 9,
      d: [
        tubule(432, 274, 516, 10, 8),
        tubule(438, 293, 522, -11, 8),
        tubule(432, 312, 510, 9, 8),
      ].join(" "),
      layers: [
        // The studs that make it "rough" ER — ribosomes sitting on its surface.
        {
          d: dots(
            [
              [450, 272], [476, 278], [500, 272],
              [456, 311], [482, 317], [502, 310],
            ],
            3,
          ),
          as: "shade",
        },
      ],
      focus: [424, 262, 108, 66],
      labelAt: [622, 316],
      leaderAt: [520, 300],
      blurb:
        "A network of folded membrane channels running out from the nuclear envelope. It carries materials across the cell, and the studded stretches of it are where proteins get assembled.",
    },
    {
      id: "golgi",
      label: "Golgi apparatus",
      tint: T.golgi,
      depth: 10,
      d: [
        cisterna(338, 326, 36, 13, 8),
        cisterna(338, 344, 30, 11, 8),
        cisterna(338, 360, 25, 10, 8),
      ].join(" "),
      layers: [
        // Vesicles budding off the ends and heading away.
        { d: dots([[292, 330], [300, 356], [386, 318]], 5), as: "fill" },
      ],
      focus: [296, 312, 88, 60],
      labelAt: [178, 392],
      leaderAt: [312, 344],
      blurb:
        "A stack of flattened sacs that packages materials made elsewhere in the cell and ships them out in bubbles, either to another organelle or through the membrane entirely.",
    },
    {
      id: "peroxisomes",
      label: "Peroxisomes",
      tint: T.peroxisome,
      depth: 11,
      d: [
        blob(352, 190, 15, 14, [1, 0.92, 1.07, 0.94, 1.05, 0.95]),
        blob(428, 176, 14, 13, [1, 0.94, 1.05, 0.93, 1.06, 0.94]),
      ].join(" "),
      focus: [336, 174, 32, 32],
      blurb:
        "Small sacs of enzymes that break down fatty acids and neutralise the toxic by-products of that work, so the reactions never spill into the rest of the cell.",
    },
    {
      id: "ribosomes",
      label: "Ribosomes",
      tint: T.ribosome,
      depth: 12,
      d: dots(
        [
          [278, 264],
          [344, 198],
          [324, 330],
          [412, 166],
          [368, 316],
        ],
        5.4,
      ),
      focus: [266, 252, 26, 26],
      labelAt: [622, 440],
      leaderAt: [418, 170],
      blurb:
        "Tiny granules where proteins are actually assembled, following instructions sent out from the nucleus. They either float free in the cytoplasm or sit studded on the endoplasmic reticulum.",
    },
  ],
};
